name: project_geolocalization
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  color: ^3.0.0
  http: ^0.13.1



  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/


  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
        - asset: fonts/Lato-BlackItalic.ttf
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-BoldItalic.ttf
        - asset: fonts/Lato-Italic.ttf
        - asset: fonts/Lato-Light.ttf
        - asset: fonts/Lato-LightItalic.ttf
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Thin.ttf
        - asset: fonts/Lato-ThinItalic.ttf
          style: italic
 